name: sb-emulator-manager-dev
services:
  emulator:
    container_name: sb-emulator-dev
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: missing
    volumes:
      - "./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD:-yourStrong(!)Password}"
      ACCEPT_EULA: "${ACCEPT_EULA:-Y}"
      EMULATOR_HTTP_PORT: "5300"
    depends_on:
      - sqledge
    networks:
      sb-emulator-dev:
        aliases:
          - sb-emulator
  sqledge:
    container_name: sqledge-dev
    image: mcr.microsoft.com/azure-sql-edge:latest
    networks:
      sb-emulator-dev:
        aliases:
          - sqledge
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA:-Y}"
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD:-yourStrong(!)Password}"

networks:
  sb-emulator-dev:
